### ISSUE TITLE
add docs for components usage

### ISSUE THREAD

**Issue by muddlebee** [w3ux/w3ux-library#128]
sample docs/tutorials will be really useful.
for e.g. https://www.npmjs.com/package/@w3ux/extension-assets

**Comment by rossbulat** [comment]
Thank you for posting this. Happy to report that https://github.com/w3ux/docs is now public and deployed to https://w3ux.org. Let's have documentation related issues on this repository moving forward.

**Comment by muddlebee** [comment]
awesome. thank you so much
